spring:
  application:
    name: square-consumer-okhttp
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
      host: livk.com

server:
  port: 8772
