server:
  port: 8888
spring:
  profiles:
    active: dev
  application:
    name: rabbit-consumer
  rabbitmq:
    host: livk.com
    username: admin
    password: admin
  cloud:
    consul:
      host: livk.com
      discovery:
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}
    stream:
      bindings:
        send-in-0:
          destination: livk-topic
          content-type: application/json
