spring:
  redis:
    host: livk.com
    password: 123456
  application:
    name: feign-consumer
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: livk.com
server:
  port: 8661

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

logging:
  level:
    com.livk.provider.api.feign: debug
