spring:
  application:
    name: feign-consumer
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
      host: livk.com
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        enabled: false
  data:
    redis:
      host: livk.com
      password: 123456
server:
  port: 8661

logging:
  level:
    com.livk.provider.api.feign: debug
