spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://livk.com:3306/livk_oauth?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: feign-provider-biz
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
      host: livk.com
  data:
    redis:
      password: 123456
      host: livk.com

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9661
